config:
  method_config:
    type: SPDHarvestConfig
    wandb_path: goodfire/spd/runs/s-e790005d
  n_batches: 2000
n_gpus: 8
partition: compute
time: "12:00:00"
merge_time: "04:00:00"
merge_mem: "200G"
